### ISSUE TITLE
Fire dragon entity ticking crash

### ISSUE THREAD

**Issue by Inteprise** [BuiltBrokenModding/AI-Improvements#30]
[crash-2022-09-04_19.29.48-client.txt](https://github.com/BuiltBrokenModding/AI-Improvements/files/9486425/crash-2022-09-04_19.29.48-client.txt)

I am playing fantasy realms modpack v6 (Minecraft version 1.16.5) and whenever a dragon, in this case a fire dragon, is spawning in the world the game crashes and i get a exit code (i forgot to screenshot) and 1 device not closed error after the crash. I am using GDLauncher.

When i turn off AiImprovements in the modlist and enter the world again the dragon spawns in like normal and i do not crash.

I found out from the ice and fire github issue tracker and did not see any type of existing report here relating to these mods interacting.

[https://github.com/AlexModGuy/Ice_and_Fire/issues/4636](url)

**Comment by bl4ckscor3** [comment]
There are different crash reasons, as well as some of the same crashes happening without AI Improvements. I have my doubts this is caused by our mod, especially because of the nature of the issue and knowing what AI Improvements does internally.
I will look at the modpack myself when I have the time and see if it happens for me as well.
