### ISSUE TITLE
server overloaded when using this mod

### ISSUE THREAD

**Issue by littlepianist** [BuiltBrokenModding/AI-Improvements#31]
![image](https://user-images.githubusercontent.com/75674050/190910884-bcff6d86-35b6-44d9-9b02-ea36171d8989.png)
https://spark.lucko.me/MFsEDtedKX

**Comment by DarkGuardsman** [comment]
![image](https://user-images.githubusercontent.com/1477330/194117222-f319a353-ebe6-40d8-bfe2-f6dfa728fd0a.png)


I don't think this is being caused by AI improvements. We are only showing in the trace due to the spawn event being triggered. Which we use to modify the AIs before they join the world. Seeing as this is coming from `canEntityDespawn` something else is likely going wrong. 

I would also need the version of MC, forge, and the mod to fully confirm. However, based on latest 1.18 we only intercept entity join world and entity spawn event.

**Comment by DarkGuardsman** [comment]
@bl4ckscor3 can you check the life cycle of forge to see if they changed the events.

**Comment by bl4ckscor3** [comment]
LivingSpawnEvent is split into multiple specific sub events, but we're only listening for the parent event and none of the specific ones. AllowDespawn is one of these sub events. I'll look into which sub event we should be listening to.

**Comment by bl4ckscor3** [comment]
Seems to be a leftover from Minecraft 1.17.1, where the EntityJoinWorldEvent broke. The mod now works without LivingSpawnEvent again. I'll push an update to remove it, should make it perform much better.

**Comment by DarkGuardsman** [comment]
Nice, good thing I poked you as I likely would have not got a chance to confirm it until next month.
